### PR TITLE
Build: add hound config

### PR DESCRIPTION
**Pull request by joeybaker**
So that we can run eslint automatically

### CODE REVIEW

**Comment by joeybaker** [comment]
@mdibaiee If you think this is a good idea, you'll have to enable this at: https://houndci.com/repos

**Comment by mdibaiee** [comment]
@joeybaker: We already have ghooks to prevent commiting without proper style, I don't really like the comment thing.

**Comment by joeybaker** [comment]
Fair enough.

**Comment by joeybaker** [comment]
Just noting: it will fail the build in addition to adding comments.

**Pull request closed without merging**
