### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by joeybaker**
This starts us off with integration tests. I think these will be easier to reason about than the pure unit-test style I was attempting before.

addresses #27

It does include a few minor fixes these tests discovered, so this is a patch release.

### CODE REVIEW

**Comment by joeybaker** [comment]
@mdibaiee I like this direction a lot more for tests. It's easier to grok even if it will give less find-grained errors. I created #28 to track progress on completion. We _could_ turn on coveralls.io or somesuch and have [AVA spit out test coverage](https://github.com/avajs/ava#code-coverage).

**Comment by mdibaiee** [comment]
@joeybaker I think I learned a thing or two from this pull-request. Thanks :grin: :+1:

**Comment by mdibaiee** [comment]
@joeybaker sure, I personally used [codecov.io](http://codecov.io/) for a few other projects, but it's up to you to choose.

**Comment by joeybaker** [comment]
Released as 2.7.2

**Comment by joeybaker** [comment]
@mdibaiee I'm not particular. I also don't have access to setup integrations. Would you mind enabling codecov.io?

**Comment by mdibaiee** [comment]
@joeybaker sure, I just enabled it, here is what needs to be modified in the Travis CI config file after coverage reports:

``` yaml
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

**Comment by joeybaker** [comment]
Cool. I'll set it up in a bit.

**Pull request merged**
