### PR TITLE
Boom

### PR DESCRIPTION
**Pull request by joeybaker**
- Adds boom to reply with 404s when necessary
- fixes a joi requirement that id's must be numbers; primary keys can also be strings

### CODE REVIEW

**Comment by mdibaiee** [comment]
Hey, thanks for the pull-request. Seems fine to me, merging! :+1:

**Comment by joeybaker** [comment]
Cool, thanks! We might have some more coming your way - we just started using this and are pretty happy with it. Thanks for building it!

**Comment by mdibaiee** [comment]
@joeybaker: That would be great! Looking forward to your pull-requests. You're welcome, I'm glad you found it useful. 😀

**Comment by mdibaiee** [comment]
published to npm `hapi-sequelize-crud@2.1.0`. https://github.com/mdibaiee/hapi-sequelize-crud/commit/07af23cb5a30a7466e42508c602db92311fa932d

**Pull request merged**
