### PR TITLE
Fix a bug in error parsing

### PR DESCRIPTION
**Pull request by joeybaker**
Fixes a case where the server could hang b/c we'd never call `reply`. Also adds some better parsing around PG errors.

This is a patch release.

### CODE REVIEW

**Comment by joeybaker** [comment]
@mdibaiee this is the kind of thing I'd just merge myself, but I figure it's better to let you see it since you've gotta push the `npm publish` button.

**Comment by mdibaiee** [comment]
You're right, it seems it's possible to have collaborators in npm, too, I didn't know that. Please feel free to merge these kind of things yourself and publish.

I just added you as collaborator: https://www.npmjs.com/package/hapi-sequelize-crud

**Comment by joeybaker** [comment]
Published as 2.5.4

**Comment by joeybaker** [comment]
Thanks @mdibaiee!

**Pull request merged**
